#!/bin/bash

## This is a script for attatching yaml header for posts going to be published on Yongfu's Blog. It is specifically suited for html_fragment output.
# argument 1 is file name

#### Part 1: Enter post date for file name ####
post_path=/home/liao/liao961120.github.io/_posts/

correct=f
while [[ "$correct" == f ]]; do

    echo -e "Enter date in\n1)'$(date +%Y-%m-%d)' format\t2)'today'\t3)'match': "
    read date

    case "$date" in
        20[0-9][0-9]-[0-9][0-9]-[0-9][0-9])
            correct=t
            echo -e "\nYou entered '${date}'\n"
            ;;
        today|2)
            correct=t
            date=$(date +%Y-%m-%d)
            echo -e "\nUse default: ${date}\n"
            ;;
        match|3)
            old_file=$(find ${post_path} -name "*${1##*/}")
            if [[ -e "$old_file" ]]; then 
                date=$(echo ${old_file##*/} | egrep -o "^20[0-9]{2}-[0-9]{2}-[0-9]{2}")
                correct=t
            else
                echo -e "\nNo matched file name.\n"
            fi
            ;;
        *)
            echo -e  "\nIncorrect date format.\n"
            ;;
    esac
done


#### Part 2: Read yaml from html_fragment ####

from=$(cat $1 | egrep '^<!--yaml$' -n | grep -Eo '^[^:]+')
to=$(cat $1 | egrep '^yaml-->$' -n | grep -Eo '^[^:]+')
(( ++from ))
(( --to ))

# Create yaml header file (will become post file)
header_path=/home/liao/liao961120.github.io/_posts/"${date}-${1##*/}"
head $1 -n $to | tail +$from > "$header_path"


#### Part 3: Append html_fragment to header file

cat $1 >> "$header_path"
echo -e "\nFile Created: \n'$header_path'"


#### Part 4: Replace <code> <pre> classes for syntax highlight

sed 's/<pre class="r"><code>/<pre><code class="r">/g' "$header_path" > "${post_path}foo.html"
sed 's/<pre class="bash"><code>/<pre><code class="bash">/g' "${post_path}foo.html" > "$header_path"
