#!/bin/bash

raw="$@"
query=${raw// /+}

if [[ "$query" =~ ^https?://.* ]]; then
  chromium-browser "$query" --disable-gpu; exit
elif [[ "$query" =~ ^//.* ]]; then
  chromium-browser 'http:'"${query}" --disable-gpu; exit
else
  chromium-browser "https://www.google.com.tw/search?q=${query}" --disable-gpu; exit
fi
