#!/bin/bash

Rscript -e "bookdown::render_book('~/local_depend/GitHubPage/my_R_book/Rmarkdown_features/index.rmd')" 

target_dir='~/liao961120.github.io/notes/rmd_features'

[[ -d ~/liao961120.github.io/notes/rmd_features ]] || mkdir ~/liao961120.github.io/notes/rmd_features

cp -r ~/local_depend/GitHubPage/my_R_book/Rmarkdown_features/_book/* ~/liao961120.github.io/notes/rmd_features


cp ~/local_depend/GitHubPage/my_R_book/Rmarkdown_features/beamer/beamer.pdf ~/liao961120.github.io/notes/beamer.pdf
