#!/bin/bash

#### Create new Rmd head file for
#### 1) bookdown::html_document2  2) bookdown::pdf_document2  3) jekyll post(html_fragment)
## $1 file name to be created
## $2 file type, defaults to html_document2

read -p "Choose type: 'pdf', 'html', 'post' > " type 

case $type in
	pdf|PDF)
		cat ~/local_depend/style_sheets/Rmd-head-pdf > $1
	    echo -e "Use PDF\nFile: $1"
		;;
	html|HTML|"")
		cat ~/local_depend/style_sheets/Rmd-head-htm > $1
		echo -e "Use HTML\nFile: $1"
		;;
	post|jekyll|fragment)
		cat ~/local_depend/style_sheets/Rmd-head-post > $1
		echo -e "Use html_fragment for Jekyll post\nFile: $1"
		;;
esac
