---
title: 'Q4: 8.14'
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message=FALSE,
                      warning=FALSE,
                      dev='svg',
                      fig.dim=c(3.6, 3.2))
library(readr)
library(tidyverse)
library(knitr)
library(kableExtra)
theme <- theme(axis.text.x = element_text(size = 7, face = "plain", angle = 30),
               axis.text.y = element_text(size = 7, face = "plain"),
               axis.title.x = element_text(size = 9, face = "bold"),
    axis.title.y = element_text(size = 9, face = "bold"))
```

```{r data_import}
sweet <- read_table2("data/T5-1.txt", col_names = FALSE)
colnames(sweet) <- c("sweet_rate", "sodium", "potassium")
```

```{r}
PCA <- prcomp(sweet, scale=F)

library(factoextra)
fviz_eig(PCA)
```

```{r}
quantiles <- qnorm(p=seq(0.25,9.75, 0.5)/10) 
PC1 <- as.data.frame(PCA[["x"]][,1])
    PC1 <- cbind(rownames(PC1), PC1)
    colnames(PC1) <- c("ID", "PC1")
    PC1 <- PC1 %>% 
        arrange(PC1) %>% mutate(quantile=quantiles)
    
PC2 <- as.data.frame(PCA[["x"]][,2])
    PC2 <- cbind(rownames(PC2), PC2)
    colnames(PC2) <- c("ID", "PC2")
    PC2 <- PC2 %>% 
        arrange(PC2) %>% mutate(quantile=quantiles)
    
PC3 <- as.data.frame(PCA[["x"]][,3])
    PC3 <- cbind(rownames(PC3), PC3)
    colnames(PC3) <- c("ID", "PC3")
    PC3 <- PC3 %>% 
        arrange(PC3) %>% mutate(quantile=quantiles)
```

```{r fig.dim=c(7.5, 3.3)}
library(ggplot2)
library(scales)
library(cowplot)
library(latex2exp)

p1 <- ggplot(PC1, aes(x=quantiles, y=PC1))+
        geom_point(color=hue_pal()(3)[1])+
        geom_text(aes(label=ID),
                  hjust=-0.1, vjust=0, size = 2)+
        scale_x_continuous(breaks = seq(-2,2, 0.5))+
        scale_y_continuous(breaks = seq(-35,35, 5))+
        labs(x=TeX("$q_{(j)}$"),
             y="PC1",
             title="PC1 Q-Q Plot")+ theme


p2 <- ggplot(PC2, aes(x=quantiles, y=PC2))+
        geom_point(color=hue_pal()(3)[2])+
        geom_text(aes(label=ID),
                  hjust=-0.1, vjust=0, size = 2)+
        scale_x_continuous(breaks = seq(-2,2, 0.5))+
        scale_y_continuous(breaks = seq(-4.5,3.5, 0.5))+
        labs(x=TeX("$q_{(j)}$"),
             y="PC2",
             title="PC2 Q-Q Plot")+ theme

p3 <- ggplot(PC3, aes(x=quantiles, y=PC3))+
        geom_point(color=hue_pal()(3)[3])+
        geom_text(aes(label=ID),
                  hjust=-0.1, vjust=0, size = 2)+
        scale_x_continuous(breaks = seq(-2,2, 0.5))+
        scale_y_continuous(breaks = seq(-2,2, 0.5))+
        labs(x=TeX("$q_{(j)}$"),
             y="PC3",
             title="PC3 Q-Q Plot")+ theme

plot_grid(p1, p2, p3, nrow = 1)
```
