---
title: "語言與社會期中作業"
author: "廖永賦"
date: "`r Sys.Date()`"
output:
  pdf_document:
    includes:
      in_header: header.tex
    latex_engine: xelatex
  html_document:
    df_print: paged
documentclass: article
geometry: margin=1in
link-citations: yes
csl: /home/liao/local_depend/style_sheets/apa_ch.csl
bibliography: lang_social.bib
urlcolor: blue
---

## 5
我覺得到了我們這一代 (1990 年後出生)應已達成階段 6「不再遭受歧視性的行為」的同化。其實對於臺灣的社會，從階段 4 過渡到階段 6 之間應該非常快速，這應與種族間的體質特徵（如膚色）差異程度有關。由於臺灣的各族群之間，外觀差異相當小，唯一能辨識族群差異的特徵大概只剩語言以及（相同語言下）發音的差異。當無法辨識出族群的差異，歧視性的態度或行為就沒有立基處，因而也就不會發生。

藉由觀察上一代的長輩們（40 歲以上），有時還能夠由漢語發音上的特徵推測其家庭的組成，但在我這一代中（20 歲左右）我已無法從發音中去區別族群。同時，相較我父母那輩會在意「誰是外省、誰是客家」，我們這代已不會談論這種事情。我們反而比較常（沒有惡意）自嘲或揶揄「誰是『天龍人』」。在我們這代沒有族群的區別[^abori]，只有「地域上（縣市）」的區別。

[^abori]: 這裡可能有個例外，是關於原住民的特殊身份。我認為這算是政府保障原住民的兩難。由於保障原住民的權益需標示出原住民的身份。有了原住民的標籤就有了差異的基礎，有了差異的基礎就有發生歧視的可能。在學校中，班上同學都會知道誰是原住民(通常不是因為特殊的口音或是可辨別的長相，總之就是會由其他同學那裡得知)，有意識或無意識可能也會對其有不同的行為。縱使行為者本身不帶任何惡意，是否構成歧視，我認為還是需由當事人本身的感受進行評斷。我不是原住民所以我不確定歧視是否發生。

## 6
就時間軸上來說，我認為這份比較表算是完整。然而由於此比較表主要是以「事件」為主，造成一些重要的限制。我認為其未能夠突顯出「日語運動」與「北京話運動」之間的一項重要差異：對於本土語言造成的衝擊。

從今日的觀點來看，「北京話運動」要比「日語運動」成功太多。這一大部份的原因也根植於這兩種語言與臺灣本土語言（此以閩南語為主）的差異程度：「閩南語與北京話差異小，而與日語差異非常大」。這個本質性上的差異造成兩個國語運動有的一項重要差異：「日語運動（必須）透過閩南語教導臺灣人日語；北京話運動不需要透過閩南語，直接以漢語教學」。因為如此，日語運動並未以強烈的手段打壓閩南語，同時也保留漢文課且以閩南語教導古文、文言文。這進一步顯示出何以兩個「國語運動」會對本土語言帶來不同的衝擊：「透過閩南語教導文言文使其與『高雅』文化有直接關聯。與高知識份子之文化結合的閩南語，其語言位階將不會是今日的情況。今日的閩南語因為北京話運動而失去與『高雅』文化的連結，而僅能作為日常生活中的溝通語言，被排除在正式教育以及學術界[^scholar]之外」。因此，閩南語被與較粗俗、低下的概念相連結，漢語則與高雅的文化相關聯。這加強了兩種語言之間的位階關係。

[^scholar]: 這裡並非獨尊「學術界」的重要性，而是指出臺灣人對於「學術界」或「知識份子」抱有較「好」或「上層」感覺的現象。這原因應根植於臺灣長期受到漢人文化的影響。


## 7
### (A)
兩個語言無法互通的人第一次遇見之時要能溝通應是個漫長而緩慢的過程。要能溝通的第一個先決條件是兩者之間至少要有一些「共同」的地方。好險我們都是人類，在認知的結構上至少會有相似之處[^comon]。最明顯的共同結構即是 joint attention：嬰兒時期即可見於人類身上的特質，嬰兒會注意到周圍之人的注意力焦點，並且望向他人注目的方向。例如，嬰兒的視線常常跟隨著母親的視線。joint attention 也是「指涉」能在人類溝通時運作的基礎。原住民與荷蘭人第一次接觸時，最早的溝通應始於比手畫腳的「指涉」，接著透過有系統性地配對語音與「類似但有些微差異」的動作逐步累積詞彙，例如：

1. 拿著一片葉子並說出：「L」
2. 拿著一片葉子再使其落下，並說出：「L D」
3. 拿著一根樹枝並說出：「B」
4. 拿著一根樹枝再使其落下，並說出：「B D」

如此便可慢慢累積詞彙，雖然勢必會製造許多歧異，然至少應可做到最為簡略的溝通。

### (B)
透過上述緩慢的學習，任一方皆有可能學會另一方的語言。然而就歷史上的關係而言，原住民似乎沒有動機要學會荷蘭語，荷蘭人因為經濟利益的需求，較有可能具備動機學習原住民的語言。而歷史遺留下來的資料也支持這個想法。荷屬東印度公司在臺灣三十多年，透過傳教士傳入基督教以及書寫系統。傳教士為方便傳教與傳達政令，學習原住民語言並且編撰字典將新港語透過羅馬拼音文字化。文字化後的新港文更為日後西拉雅族用於契約簽訂，形成了新港文書[@2018d; @2018e]。


[^comon]: 有關 Bonus 題的題外話： 或許人類根本不可能與 heptapods 成功溝通。Dr. Banks 與 heptapods 之間的溝通始於「指涉」（Banks 指向自己並寫著 Louise），然而外星人要理解這個動作的意義必須先有「指涉」的概念，且其注意力運作的方式需與人類類似（當 Banks 指向自己時，heptapods需要知道必須將注意力放在 Banks 「手」指之處而非「手肘關節」指向之處）。

## 8

### 幸福路上

《幸福路上》以閩南語作為日常生活中的主要語言，我覺得相當符合當時社會的情況。電影中的地點設定為臺北，臺北作為一個移居者匯集的地區，生活中的語言使用應以當時最流通的語言為主（溝通指數最高），而閩南語應為當時民間最流通的語言。

電影中另一個有趣的語言現象即為主角小琪的語言。《幸福路上》以小琪的故事作為主幹，而小琪的故事其實就是《幸福路上》導演宋欣穎自身的成長故事[-@2018; -@2018a; -@2018b; -@2018c]。根據導演的受訪，馬上就可以回答電影中這個「奇怪」的語言現象—為何生長在父母皆使用閩南語的家庭，小琪仍然較常使用中文（漢語）？電影忠實地呈現了**導演宋欣穎自身語言使用的情況**：

> 我的外婆是個有原住民血統、吃檳榔的外婆，可是我家裡都講台語，而事實上我自己又不太會講（台語）。等我到了美國，看到他們的移民家庭裡，父母都使用母語，除了中文還有西班牙語、和甚至非洲語等等，可是小孩都用英文回答他們，我覺得這很有趣，怎麼會跟我們家一樣？[-@2018a]

小琪的現象或許並非罕見。例如，研究顯示通常同儕相對於父母對使用何種語言有較大的影響力[@stanford2008]，或許在當時的國語政策下，同儕間（在學校）的溝通語言變成漢語為主，造成小琪日後以漢語作為主要語言。另一可能的原因為性別。以我所知的例子，
1. 我外公為外省籍的老兵，不會講閩南語，但其常不在家。我外婆為本省籍，講閩南語[^grandma]。因此可合理推測我母親幼時，家庭應該以閩南語為主。然我母親雖會講閩南語，但不算是最流利的那種（少了點母語使用者那種流暢的口音，某些詞彙也不清楚）。
2. 這學期我聽中文系的張麗麗老師提及她自身的狀況：與我母親相同，老師也是在外省（父）—本省閩南（母）家庭長大的。老師說她以及妹妹不會閩南語，但她的兄弟皆會流利的閩南語。



[^grandma]: 有趣的是，我外婆跟我（還有跟我目前 8 歲的表弟）說話時，會自動改成使用漢語。而我小時候在外婆家住過一段時間，那時正好是我開始學會講話的時間。不知道這是否與我低落的閩南語程度有關。


## 9

語言與思維的關係相當複雜。縱使最極端版本的 Sapir-Whorf Hypothesis—語言決定論（Linguistic determinism）被認為是錯誤的，語言仍有可能以其他更細微的方式影響思維。依據思維相對於語言運作的時機，可將之區分為「說話前的思考（Thinking for speaking）」、「運用語言思考（Thinking with language）」、「語言對思考的後續影響（Thinking after language)」[@wolff2010]。以下簡單各舉一例：

1. 說話前的思考：有些語將動作的方式（manner）表示於動詞，而將動作的方向（path）表示於其它詞類（如副詞），英語、中文即為這種語言（「run out」、「跑出去」）。另一些語言比較重視動作的方向（path）而將其用於動詞，將動作的方式（manner）表示於其它詞類，如法語、日語、希臘語。這些不同語言上的結構差異，造成其使用者開始說話前，注意力關注的焦點不同。例如，希臘語使用者比起英語使用者更傾向注意動作的方向（path）[@papafragou2008]。

2. 運用語言的思考：運用語言的思考最顯著的一個例子是「精確」的數量。人類以及許多其他動物，天生就對極小的數量（小於3或4）的數量有絕對的概念；對大量的數量有約略的概念；但對精確的「數字」，如「33」，是後天習得的。明確的證據指出精確的數字概念與語言之間的關聯 [@dehaene1999; @spelke2001; @frank2008]。沒有語言，或語言中不具有數字系統，人類將無法以精確的數量進行思考。

3. 語言對思考的後續影響：前述兩種語言與思維之間的關係直接與語言有所關聯，即思考本身是為了表達，或是透過語言進行思考，語言似乎直接參與了思考歷程。「語言對思考的後續影響」指的則是不涉及語言本身的思考：在長期使用特定語言下，是否會對思維產生影響。其中一項支持的證據來自語言中是否舉有單複數。日語、中文等語言的名詞，沒有單數或複數型態的差別；英語則必須指出名詞為單數或複數。因此，英語使用者可能會傾向將注意力集中在「個體」的特質，而日語或中文的使用者則可能傾向將注意力集中在「共同」的特質。例如，英語使用者可能較注意椅子的形狀，而日語、中文使用者則較注意椅子的材質。此假設受到 @li2009 的研究支持。

這些研究證據顯示語言以不同種方式影響思維的可能。然關於 Daniel Everett 對於 Pirahã 人的想法：「他們的語言沒有時態，他們真正活在當下之中」，似乎隱含更複雜的因素。首先，我同意這句話的後半段：人類在進入大規模社會後，先是曆法，接著時鐘的發明似乎改變人類對於時間的概念，大家開始擔心時間的流逝，並且開始「預約未來」（排行事曆、約會時間等）。Pirahã 人生活在沒有現代時間概念的社會中，且其生活方式也無須擔心是否有事情未完成，因此其「活在當下」顯得相當合理。然我認為難以使用「他們的語言沒有時態」作為理由。從 Pirahã 人的文化可以很明顯地發現其許多部份皆支持著 Pirahã 人「活在當下」，例如簡單的物質技術（所以不須從事大規模的生產）、從事漁獵採集（所以比起農耕更加不勞力密集）、沒有強烈的物質需求（只向 Everett 要求一些簡單的物資）等。文化本身即是強而有力的解釋，能夠說明 Pirahã 人「活在當下」。忽略這些文化因素而單以語言的結構作為解釋顯得相當不合理。


## Bonus
電影中不只一次出現語言與意圖的關係—詞彙不只帶有字面上的意義，隨著使用者的不同意圖或是既存的偏見，造成字彙有不同的詮釋意義。例如，電影開始不久後，Colonel Weber 兩度拜訪 Dr. Banks 時，Banks 提及梵語（Sanskrit）「戰爭（war)」的詞彙以及意義：

> (Colonel 從學校離開前的對話)  
> **Louise**: Are you going to ask Danvers next?...Before you commit to him, ask him the Sanskrit word for war and its translation. 
> 
> (Colonel 半夜搭直昇機拜訪 Dr. Banks)  
> **Colonel**: He says it means "an argument". What do you say it means?  
> **Louise**: A desire for more cows.

我認為這裡展現出電影對於語言的多義性的重視，以及其對於人類的影響。對相同詞彙的不同翻譯，展現出非常不一樣的意圖：一個表現出「敵意」（"argument"），另一個則相對和平（"desire for more cows"）—在一念之間，不同的詮釋可能造成衝突或和平。

語言與意圖之間的關聯在電影中的另一個地方更加地被突顯了出來：

> (Dr. Banks 在翻譯擷取的中文)  
> **Louise**: Colonel, those are all tile sets in mah-jongg. Are they using a game to converse with their heptapods?  
> **Colonel**: Maybe. Why?  
> **Louise**: Well, let's say that I taught them chess instead of English. Every conversation would be a game. Every idea expressed through opposition, victory, defeat.  
> **Louise**: You see the problem?  
> **Louise**: If all I ever gave you was a hammer...  
> **Colonel**: Everything's a nail.

這裡更加入了語言的「譬喻」特性，透過譬喻語言的意義得到了驚人的擴充。「譬喻」在這裡或許也顯示出人類喜好尋找語言的「言外之意」的特性，也顯示溝通過程中從來不是簡單的「送出」與「接收」，而是在過程中相互不斷進行揣摩與推論。語言與溝通是一個非常動態的過程。

電影中的其它部份，主要闡述人類的思考如何受限於我們生存的世界、概念以及語言。電影中代有非常強烈的沃爾夫的色彩，認為學習一種結構非常特異的語言能為大腦帶來全面性的改變，甚至超越我們所生存的三度空間，感知超越「現在」的時空。我想這邊屬於電影比較浪漫、自由創造的部份，也同時是這部電影中最吸引人的地方，縱使我多半不認同這些主張。

## 參考資料{#reference} 

