---
link-citations: yes
output:
  html_fragment:
    includes:
    number_sections: no
---

<!--yaml
---
layout: post
mermaid: false
mathjax2: false
mathjax: false
highlight: true
title: "jieba：使用自訂詞庫斷詞"
description: ""
tags: [Text, Mining, R, 中文]
---
yaml-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.dim = c(7, 4),
	message = FALSE,
	warning = FALSE,
	comment = "",
	out.width = "100%"
)
library(knitr)
```

在進行中文 Text Mining 前處理時，必須先經過斷詞處理。社群當中存在相當好的斷詞處理工具，如 [jieba](https://github.com/fxsjy/jieba)。但斷詞時常遇到一個問題：**文本中重要的詞彙因為不常見於其它地方而被斷開，像是人物角色名稱**。要處理這個問題，需將自訂詞庫提供給斷詞套件，其才不會將重要詞彙斷開。
<!--more-->

這邊將使用 [jiebaR](https://github.com/qinwf/jiebaR)，介紹使用自訂詞庫的斷詞方式。同時也提供一種自訂詞庫的製作方式。

## 示範語料

這裡使用金庸**[神雕俠侶](https://zh.wikipedia.org/wiki/%E7%A5%9E%E9%B5%B0%E4%BF%A0%E4%BE%B6)第三十二回 --- 情是何物**作為斷詞的文本。武俠小說在此是個很好的例子，因為裡面有許多人物名稱和專有名詞。


## 維基百科角色列表

[神鵰俠侶角色列表](https://zh.wikipedia.org/wiki/%E7%A5%9E%E9%B5%B0%E4%BF%A0%E4%BE%B6%E8%A7%92%E8%89%B2%E5%88%97%E8%A1%A8)



```{r}
library(readr)
library(rvest)
library(stringr)
library(dplyr)
library(jiebaR)

data <- read_html("神鵰俠侶角色列表.html") %>%
    html_nodes("ul") %>% html_nodes("li") %>%
        html_nodes("a") %>% html_text()
```

```{r}
data <- unique(data)

data[1:3]
data[21:25]
data[207:211]
```



```{r}
data <- as_data_frame(data)
data <- data[43:548,] %>% unique()
data <- data[-c(2, 22, 128, 139,200:209),] %>% rbind("過兒")
write_csv(data, "sdxl_wordlist.csv")
```





<p style="text-align:right;font-size:8px;margin-top:0px; margin-bottom:0px;padding-top:0px;padding-bottom:0px">
上次更新：`r Sys.Date()`
</p>
