---
title: "報告"
subtitle: "副標題"
author: Yongfu Liao
date: March 13, 2018
output:
  ioslides_presentation:
    fig_height: 3
    css: ../style_sheets/presentation_style.css
    incremental: false
    logo: tux.svg
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, comment="")
library(DiagrammeR)
```


## 中文 

- **粗體**
- <div class="red2">蘋方?</div>

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document.

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

A Graph
```{r fig_retina=1}
grViz("
graph { //non-directed graph
    graph [layout = neato]  //layout = dot|neato|twopi|circo|fdp
    
    node [shape = circle,
          style = filled,
          color = orange]

    node [fillcolor = red]
    a [label = '受']

    node [fillcolor = orange1]  //orange1-4
    b [label = '總攻']
    c [label = '強攻']
    d [label = '健氣攻']

    edge [color = grey]
    {b c d} -- a
    }")
```

## Slide with Plot {.smaller}

```{r echo=TRUE}
grViz('
digraph { //directed graph
    "總攻" -> "受";
    "強攻" -> "受";
    "健氣攻" -> "受";
     }'
)
```

