---
title: "Google 表單即時回饋"
date: "`r Sys.Date()`"
output: 
    html_document:
        css: ./style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
source("./bootstrap_fc.R")
date <- lubridate::with_tz(Sys.time(), tzone = "Asia/Taipei")
```

```{r}
# Button trigger modal
button_bs("填寫表單", data_toggle="modal", data_target="#sheet", class="primary pull-left")
```

```{r}
# iframe for Google Form
iframe <- HTML('<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeE-ke7yhlU3XRDIhw7vRL-mnYLi-jTOYF8Pz4ZLINjV53z2A/viewform?embedded=true" style="position: relative; height: 360px; width: 100%;" frameborder="0" marginheight="0" marginwidth="0">載入中…</iframe>')

modal(id="sheet", modal_header = "Google 表單", modal_body=iframe)
```


<br><br><br>

```{r}
library(htmltools)
HTML('
<script src="https://cdn.datacamp.com/datacamp-light-latest.min.js"></script>
    <div data-datacamp-exercise data-lang="r">
        <code data-type="pre-exercise-code">
            data <- readr::read_csv(url("https://docs.google.com/spreadsheets/d/e/2PACX-1vQz4zjZfhWBYYRuW2Zhhx-sXvnlrS6vpvcgP0cJPdvsQI-6eKggXmpaWbu4dgbMQgcOHv0NQxL8a_K_/pub?output=csv"))
            data <- as.data.frame(data)
            colnames(data) <- c("DateTime", "Token", "Score")
            data <- data[which(data$Score!=100),]
            score <- function(token) {
                i <- which(data$Token==token)
                data[i,]
            }
	    </code>
        <code data-type="sample-code">
            # Put Token in "". Ex: score("abcde123")
            score("Enter_your_Token")
	    </code>
    </div>
')
```

