---
title: "My Bash Notes"
subtitle: "A Quick Reference"
author: "[Yongfu Liao](https://liao961120.github.io/)"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
link-citations: yes
output:
  bookdown::html_document2:
    css: /home/liao/local_depend/style_sheets/style.css
    df_print: kable
    toc: true
    toc_depth: 2
    toc_float:
        collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	comment = ">",
	dev='svg',
	fig.dim = c(5.5, 3.5)  # (width, height)
)
```

Common Syntax
========

## case
```bash
case "$var" in
	pattern_1)
		commands
		;;
	pattern_2)
		commands
		;;
esac
```

## if
```bash
if [[ ]]; then
	commands
elif [[ ]]; then
	commands
else
	commands
fi
```

### Logical Operators

```bash
-eq # equal
-ne # not equal
-lt # less than
-le # less than or equal
-gt # greater than
-ge # greater than or equal
```

```bash
[[ $num1 -eq $num2 ]] && echo "true"
```


## Conditionals (Square brackets)

```bash
[ -f file.txt ] && echo "File exist" 
[ -s FB_title.txt ] && echo "File size > 0"
[ -d dir/ ] && echo "Dir exist"
[ -z "$var" ]      # Whether $var is empty
```


## Loops

### for

#### With Sequence of Numbers

**Tradional Type**
```bash
for i in {1..3}; do
	commands
done
```

**C lang Type**
```bash
for (( i=0; i<=5; ++i )); do
	commands
done
```

#### Other Sequences

```bash
for i in A B C D; do
	commands
done
```

```bash
for i in {A..D}{1..3}; do
	commands
done
```


Common Techniques
========

## Parameter Expansions

### Match the last expresion
```{bash}
> ~/Desktop/foo.txt
file_path=~/Desktop/foo.txt
echo ${file_path##*/}
```

## Copy Previous Command to file

```bash
cat ~/bash_pract/rmd-head.txt >> ~/bash_pract/doc.Rmd
echo "!!" >> ~/bash_pract/cmd_hist
```

Then the command appends literal `cat ~/bash_pract/rmd-head.txt >> ~/bash_pract/doc.Rmd` to the end of `cmd_hist`. Note that this **works only on the command line**, not shell scripts.


## Expansion with text

Download all web pages starting from `www.millionbook.net/wx/j/jingyong/sdxl/001.htm` to `www.millionbook.net/wx/j/jingyong/sdxl/041.htm`:

```bash
url=http://www.millionbook.net/wx/j/jingyong/sdxl/
wget "$url"{001..041}".htm"
```

RegEx
========

**MetaCharacters**

- `.`: Any character.

- `+`: **1 or more**, e.g. `s+aa` matches 1 or more `s` followed by `aa`.

- `*`: **0 or more**, e.g. `s*aa` matches 0 or more `s` followed by `aa`.

- `{#}`: **Exact #**, e.g. `s{2}` matches strings with exactly 2 `s`(equivalent to `ss`).
	- `{#_1, #_2}`: **Between #_1 & #_2**.

- `(<some.char>)`: Use `(` & `)` to **group**
	- `(na){2}`: matches ba**nana**.


String Manipulation
========

## cut

`list.txt`:
```
10/04 2018,xaringan
09/28 2018,pttR-intro
```

Read one line of `list.txt` in each loop,
cut the line into 2 fields, seperated by `,`.
```bash
while read p; do
  date=$(echo "$p" | cut -d ',' -f 1)
  file=$(echo "$p" | cut -d ',' -f 2)
done < list.txt
```

## printf

More consistent then `echo`, 
can use special characters like `\\n`.
```bash
printf "$date &nbsp;&nbsp; [$file](${file}/index.html)\n\n"
```

## cat

`cat` the text between the two `_EOF_`.
```bash
cat << _EOF_
---
title: Slides
---

# List of Slides
<br><br>
_EOF_
```

`cat` the text between the two `_EOF_`, then **redirect the text to `index.md`**.
```bash
cat >> index.md  << _EOF_
---
title: Slides
---

# List of Slides
<br><br>
_EOF_
```

## grep

Search files in working dir that contain certain string:
```bash
grep -r ".img" *
```

Search file names in working dir that contain certain string:
```bash
ls | grep ".txt"
```


## Compare Files

```bash
ls dir1 > file1.txt
ls dir2 > file2.txt
diff file1.txt file2.txt
```

Navigation
========

## File Manipulation

### Recursive Rename

Systematically rename multiple files by `for` loop.

```{bash, preprocess-dir, include=FALSE}
cd ~/bash_pract && rm -r dir
mkdir dir dir/dir2
touch dir/{01..03}-file.txt dir/README
```


Original files in the working dir:
```{bash}
ls ~/bash_pract/dir
```

Then, running the code below:
```{bash}
cd ~/bash_pract/dir

for i in {01..03}; do 
	mv $(echo $i'*') $(echo $i'.txt')
done

ls
```

## Soft Link

Syntax: `ln -s <target> <link-name>`

e.g.
```{bash}
cd ~/bash_pract
echo "Before:
$(ls -l)"

ln -s $(pwd)/dir/foo.txt $(pwd)/foo-sym

echo "
After:
$(ls -l)"
```

```{bash include=FALSE}
rm ~/bash_pract/foo-sym
```

Reading Files
========

## Loop Over Every Line of a File
```bash
while read p; do
  date=$(echo "$p" | cut -d ',' -f 1)
  file=$(echo "$p" | cut -d ',' -f 2)
done < list.txt
```

## Loop Over Several Files
```bash
while IFS=$'\t' read -r title tags link
do
  printf "${title}/n"
  printf "${tags}/n"
  printf "${link}/n/n"
done < <(paste FB_title.txt FB_tags.txt FB_link.txt)
```

Function Flows
========

```bash
[ -f file.txt ] && exit 0
```

```bash
sleep 10 # seconds
```


Network
========

## Curl

```bash
curl --silent --show-error --fail https://raw.githubusercontent.com/Rbloggers/web/posts/FB_title.txt > FB_title.txt
```

- `--silent`: Don't print process to std. output
- `--show-error`: Print error message to std. output
- `--fail`: Return empty file if 404


## Setup SSH

### Server Setup{-}
Install SSH Server (so be connected by a remote client):
```bash
sudo apt-get install openssh-server
```

Configure:
```bash
sudo gedit /etc/ssh/sshd_config
```

> Port 22
>
> PasswordAuthentication yes
>
> PermitRootLogin yes

Findout IP address locally: `hostname -I`


### Client Setup{-}

Access from remote via SSH:

Syntax: `ssh <server-user-account>@<ip>`

e.g.
```bash
ssh liao961120@192.168.2.110
```


Remote Control Via SSH
========

## Hardware Configuration

Enable WakeOnLane(WOL) at BIOS: 
	
1. `Power Management Setup` > `WOL: enabled`[^wol]
2. `Power Management Setup` > `deep power off mode: disabled`[^poff]


[^wol]: There may be different names for WOL, such as 'Wake Up on Lan', 'Automatic Power Up', 'Resume by LAN', 'Power Up On PCI Device', 'PME Event Wake Up', etc.
[^poff]: This keeps the power for NIS to turn on the computer when receiving a signal from web.
[^utc]: Note the date time is in [Coordinated Universal Time (UTC) Standard](https://en.wikipedia.org/wiki/Coordinated_Universal_Time), so it's -8 hrs from the time in Taiwan.

## wakeonlan

wakeonlan -i <broadcast-ip> <MAC>

```bash
wakeonlan -i 192.168.2.255 44:87:fc:a1:0b:cc
wakeonlan -i $rm_ip_b $rm_MAC
```

## SSH login

ssh liao961120@<ip>

```bash
ssh liao961120@192.168.2.110
ssh $ssh_pc
```

## SSH logout & suspend computer

Use `sudo shutdown 0` to leave. Remember to enable `Power of Mode` in BIOS, so you can WOL to open the computer again.

## Variable Definition (in `~/.bashrc`)
```bash
rm_MAC="44:87:fc:a1:0b:cc"
rm_ip="192.168.2.110"
rm_ip_b=`bash ~/ip2ipb.sh $rm_ip`
ssh_pc="liao961120@$rm_ip"
```

Other Resources
===========

- [Bash scripting cheatsheet](https://devhints.io/bash)